Forgot pwd & reset pwd routes
Weather-Vortex/weather-vortex-server pull request #78
Opened 2021-09-17 08:16 UTC by silviazandoli

aggiunti metodi PUT /auth/forgotPassword e PUT /auth/resetPassword dove posso modificare la password, invio email con link del client

Testato con Postman e funziona
Istruzioni per testarlo su Postman:
1) loggarsi
2) fare una chiamata auth/forgotPassword-> mi verrà inviata una email con link del client, dove posso visualizzare il token
3) faccio poi su postman la chiamata auth/resetPassword dove come parametri scrivo la nuova password e il token che ho preso dalla email, come si può vedere in figura
![Cattura](https://user-images.githubusercontent.com/29338213/133748961-d74fb3e4-ab48-4c48-a8ca-ea2537c46a7b.PNG)

Se mi loggo di nuovo dovrò ora utilizzare la nuova password

2021-09-17 10:55 UTC, igor-lirussi approved these changes

2021-09-17 13:56 UTC, Daniele-Tentoni requested changes
- [x]  A cosa serve il modulo lodash? Mi sembra di capire che venga usato solo per modificare l'oggetto User. Perché viene usato solo in quel punto? Si può usare il Javascript puro? Che vantaggi porta usare questo modulo? 

- [x]  Riesci ad aggiungere almeno un test automatico per ogni chiamata oltre alla già ben documentata procedura con Postman?

2021-09-19 08:26 UTC, silviazandoli commented
@Daniele-Tentoni per il test ci provo, mi sa che proverò a installare il  "mailslurp" che serve per provare a simulare l'invio della mail

2021-09-21 19:46 UTC, Daniele-Tentoni requested changes

2021-09-21 19:46 UTC, Daniele-Tentoni commented on src/models/user.model.js
> +    data: String,
Perché data e non type? A cosa si riferisce?

2021-09-21 19:46 UTC, Daniele-Tentoni commented on src/routes/auth.routes.js
> +router.put("/forgotPassword", auth, authStorage.forgotPassword);
Come faccio ad essere autenticato se non mi ricordo la password?

2021-09-22 07:05 UTC, silviazandoli commented
@Daniele-Tentoni ho tolto l'auth. Riesci a vedere se i test da te funzionano tutti? A me è comparso errore in GET forecast for cesena

2021-09-22 16:28 UTC, Daniele-Tentoni approved these changes

2021-09-22 16:34 UTC, merged